[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/html/index.html"
  status = 200

[[redirects]]
  from = "/catalogo"
  to = "/html/catalogo.html"
  status = 200

[[redirects]]
  from = "/sobre"
  to = "/html/sobre.html"
  status = 200

[[redirects]]
  from = "/contato"
  to = "/html/contato.html"
  status = 200

[[redirects]]
  from = "/produto"
  to = "/html/produto.html"
  status = 200

[[redirects]]
  from = "/clube"
  to = "/html/clube.html"
  status = 200